# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mvvm-c-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mvvm-c-demo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'mvvm-c-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mvvm-c-demoUITests' do
    # Pods for testing
  end

end
